/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import org.apache.log4j.Logger;

import Client.Controlleurs.ServerConnect;
import Modele.Car;
import Modele.CardState;
import Modele.Part;
import Modele.RepairCard;
import Modele.RepairCardDAO;
import Modele.User;
import Serveur.Controlleurs.Serveur;

/**
 *
 * @author Carbon5
 */
public class PanelDetailOperation extends JPanel {
    /**
     * Creates new form PanelDetailOperations
     */
    public PanelDetailOperation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblDetailOp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        
        
        tfidVehicule = new javax.swing.JTextField();
        tfidTechnicien = new javax.swing.JTextField();
        jtfState = new javax.swing.JTextField();
        
        tfidVehicule.setEditable(false);
        tfidTechnicien.setEditable(false);
        jtfState.setEditable(false);

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ArrayList<String> state = new ArrayList<String>();
        for (CardState aState : CardState.getAllState()){
        	model.addElement(aState.getDescription());
        }
        
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        ArrayList<String> parts = new ArrayList<String>();
        for (Part aPart : Part.getAllParts()){
        	model2.addElement(aPart.getNamePart());
        }
        
        DefaultComboBoxModel model3 = new DefaultComboBoxModel();
        ArrayList<String> parts2 = new ArrayList<String>();
        for (Part aPart : Part.getAllParts()){
        	model3.addElement(aPart.getNamePart());
        }
        
        DefaultComboBoxModel model4 = new DefaultComboBoxModel();
        ArrayList<String> parts3 = new ArrayList<String>();
        for (Part aPart : Part.getAllParts()){
        	model4.addElement(aPart.getNamePart());
        }
        
        
        cbPiece1 = new javax.swing.JComboBox<>(model2);
        cbPiece2 = new javax.swing.JComboBox<>(model3);
        cbPiece3 = new javax.swing.JComboBox<>(model4);
        jLabel4 = new javax.swing.JLabel();
        lblQté1 = new javax.swing.JLabel();
        lblQté2 = new javax.swing.JLabel();
        lblQté3 = new javax.swing.JLabel();
        jtfQte1 = new javax.swing.JTextField();
        jtfQte2 = new javax.swing.JTextField();
        jtfQte3 = new javax.swing.JTextField();
        btnValide = new javax.swing.JButton();
        btnSuspend = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        
        

        jLabel5.setText("jLabel5");

        lblDetailOp.setText("DETAIL DE L'OPERATION");

        jLabel2.setText("INFORMATION________________________________________________");

        jLabel3.setText("OPERATION__________________________________________________");

        tfidVehicule.setText("");

        tfidTechnicien.setText("");

        jLabel4.setText("Pièce nécessaire");

        lblQté1.setText("Quantité");

        lblQté2.setText("Quantité");

        lblQté3.setText("Quantité");

        jtfQte1.setText("    ");

        jtfQte2.setText("    ");

        jtfQte3.setText("    ");

        btnValide.setText("Valider");

        btnSuspend.setText("Suspendre");

        jLabel10.setText("Pièce nécessaire");

        jLabel11.setText("Pièce nécessaire");

        jLabel6.setText("jLabel6");

        jLabel12.setText("jLabel12");

        jLabel13.setText("ID véhicule:");

        jLabel14.setText("ID technicien");

        jLabel15.setText("Statut");

        jLabel16.setText("jLabel16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSuspend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValide, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDetailOp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cbPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblQté3)
                                .addGap(18, 18, 18)
                                .addComponent(jtfQte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbPiece1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbPiece2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQté2)
                                    .addComponent(lblQté1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfQte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfQte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfidTechnicien, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfidVehicule)
                                    .addComponent(jtfState, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetailOp)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfidVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfidTechnicien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfQte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbPiece1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(lblQté1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPiece2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQté2)
                            .addComponent(jLabel11)))
                    .addComponent(jtfQte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQté3)
                    .addComponent(jLabel10)
                    .addComponent(jtfQte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValide)
                    .addComponent(btnSuspend))
                .addContainerGap())
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnValide;
    private javax.swing.JButton btnSuspend;
    private javax.swing.JComboBox<String> cbPiece1;
    private javax.swing.JComboBox<String> cbPiece2;
    private javax.swing.JComboBox<String> cbPiece3;
    private javax.swing.JLabel lblDetailOp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblQté1;
    private javax.swing.JLabel lblQté2;
    private javax.swing.JLabel lblQté3;
    private javax.swing.JTextField jtfState;
    private javax.swing.JTextField tfidVehicule;
    private javax.swing.JTextField tfidTechnicien;
    private javax.swing.JTextField jtfQte1;
    private javax.swing.JTextField jtfQte2;
    private javax.swing.JTextField jtfQte3;
    final static Logger logger = Logger.getLogger(Serveur.class);

    // End of variables declaration    
    
    class BoutonListener implements ActionListener{
    	JPanel frame=null;

    	/**
     	* Class constructor
     	* @param f 
     	*/
    	public BoutonListener  (JPanel f){
    		this.frame=f;
    	}
	
    	/**
    	 * Method generate component action
    	 * @param arg0 
    	 */
    	public void actionPerformed(ActionEvent arg0){
    	
    		String namePart = ""+(String) cbPiece1.getSelectedItem()+"";
    		String quantite = jtfQte1.getText();
    		
    		ArrayList<String> data = new ArrayList<String>();
    		data.add(namePart);
    		data.add(quantite);
    		data.add(""+User.getAllUsers().get(0).getId());
    		String identifier = "SelectAllParts";
    		logger.info("affichage combobox");
    		new ServerConnect(data, identifier, frame);
    		
            

    	}
	}
}
