package Vues;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;

import org.apache.log4j.Logger;

import Client.Controlleurs.ServerConnect;
import Modele.Car;
import Modele.CardState;
import Modele.Part;
import Modele.RepairCard;
import Modele.RepairCardDAO;
import Modele.User;
import Serveur.Controlleurs.Serveur;
import Vues.PanEntreeStock.BoutonListener;

/**
 *
 * @author Carbon5
 */
public class PanelDetailOperation extends JPanel {
    /**
     * Creates new form PanelDetailOperations
     */
    public PanelDetailOperation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblDetailOp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        
        tfidVehicule = new javax.swing.JTextField();//RepairCard.getPrioritaryCard().getidcar()
        tfidTechnicien = new javax.swing.JTextField(User.getManager().getId());
        jtfState = new javax.swing.JTextField();//RepairCard.getPrioritaryCard().getStatutCar()
        
        
        jtfPiece1 = new javax.swing.JTextField();//RepairCard.getPrioritaryCard().getDefect().getDescription()
        jtfPiece2 = new javax.swing.JTextField();
        jtfPiece3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblQté1 = new javax.swing.JLabel();
        lblQté2 = new javax.swing.JLabel();
        lblQté3 = new javax.swing.JLabel();
        jtfQte1 = new javax.swing.JTextField();
        jtfQte2 = new javax.swing.JTextField();
        jtfQte3 = new javax.swing.JTextField();
        btnValide = new javax.swing.JButton();
        btnSuspend = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblOpe1 = new javax.swing.JLabel();
        lblOpe2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblOpe3 = new javax.swing.JLabel();
        
        tfidVehicule.setEditable(false);
        tfidTechnicien.setEditable(false);
        jtfState.setEditable(false);
        jtfPiece1.setEditable(false);
        jtfPiece2.setEditable(false);
        jtfPiece3.setEditable(false);
        
        

        jLabel5.setText("jLabel5");

        lblDetailOp.setText("DETAIL DE L'OPERATION");

        jLabel2.setText("INFORMATION________________________________________________");

        jLabel3.setText("OPERATION__________________________________________________");

        tfidVehicule.setText(RepairCard.getPrioritaryCard().getidcar());

        tfidTechnicien.setText("");

        jLabel4.setText("Pièce nécessaire");

        lblQté1.setText("Quantité");

        lblQté2.setText("Quantité");

        lblQté3.setText("Quantité");

        jtfQte1.setText("    ");

        jtfQte2.setText("    ");

        jtfQte3.setText("    ");

        btnValide.setText("Valider");
        btnValide.addActionListener(new BoutonListener(this));

        btnSuspend.setText("Suspendre");

        jLabel10.setText("Pièce nécessaire");

        jLabel11.setText("Pièce nécessaire");

        lblOpe1.setText("Vitre");
//RepairCard.getPrioritaryCard().getDefect().toString()
        lblOpe2.setText("Pneu");

        jLabel13.setText("Numéro de puce:");

        jLabel14.setText("ID technicien");

        jLabel15.setText("Statut");

        lblOpe3.setText("Renovation phare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSuspend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValide, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDetailOp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOpe1)
                            .addComponent(lblOpe2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jtfPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblQté3)
                                .addGap(18, 18, 18)
                                .addComponent(jtfQte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOpe3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfPiece1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfPiece2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQté2)
                                    .addComponent(lblQté1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfQte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfQte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfidTechnicien, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfidVehicule)
                                    .addComponent(jtfState, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetailOp)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfidVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfidTechnicien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblOpe1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfQte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPiece1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(lblQté1)))
                .addGap(18, 18, 18)
                .addComponent(lblOpe2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPiece2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQté2)
                            .addComponent(jLabel11)))
                    .addComponent(jtfQte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(lblOpe3)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQté3)
                    .addComponent(jLabel10)
                    .addComponent(jtfQte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValide)
                    .addComponent(btnSuspend))
                .addContainerGap())
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnValide;
    private javax.swing.JButton btnSuspend;
    private javax.swing.JTextField jtfPiece1;
    private javax.swing.JTextField jtfPiece2;
    private javax.swing.JTextField jtfPiece3;
    private javax.swing.JLabel lblDetailOp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lblOpe2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel lblOpe3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblOpe1;
    private javax.swing.JLabel lblQté1;
    private javax.swing.JLabel lblQté2;
    private javax.swing.JLabel lblQté3;
    private javax.swing.JTextField jtfState;
    private javax.swing.JTextField tfidVehicule;
    private javax.swing.JTextField tfidTechnicien;
    private javax.swing.JTextField jtfQte1;
    private javax.swing.JTextField jtfQte2;
    private javax.swing.JTextField jtfQte3;
    final static Logger logger = Logger.getLogger(Serveur.class);

    // End of variables declaration    
    
    class BoutonListener implements ActionListener{
    	JPanel frame=null;

    	/**
     	* Class constructor
     	* @param f 
     	*/
    	public BoutonListener  (JPanel f){
    		this.frame=f;
    	}
	
    	/**
    	 * Method generate component action
    	 * @param arg0 
    	 */
    	public void actionPerformed(ActionEvent arg0){
    		//We substract jtfPiece1 to the original Stock of the referenced part.
    		//Part.getAllParts().get(0).setStock(Part.getAllParts().get(0).getStock() - 1);
    	
    		if(Part.getAllParts().get(0).getStock() < 10){
    			int result = JOptionPane.showConfirmDialog(null, 
    					   "Le stock de pièces choisi est désormais inférieur à 10, voulez-vous commander des pièces ?","Attention", JOptionPane.YES_NO_OPTION);
    			if(result == JOptionPane.NO_OPTION) {
    				JOptionPane jop1 = new JOptionPane();
    				jop1.showMessageDialog(null, "Opération validée", "Information", JOptionPane.INFORMATION_MESSAGE);
    			//Set varialble State of the current Part to "Réparé"
    			    System.exit(0);
    			}
    			else{
    				PanEntreeStock jp = new PanEntreeStock();
    			}
    		}
    		
        	}
    		
    	}
    	
	}
    
    /**
     * Class Bouton2Listener listens button Valider
     */
    class Bouton2Listener implements ActionListener{
    	JPanel frame=null;

    	public Bouton2Listener  (JPanel f){
    	this.frame=f;
    	}
    	
        /**
         * Method generate button action
         * @param e 
         * @see dispose()
         */
    	public void actionPerformed(ActionEvent e){
            //Initialize varialble State of the current Part to "En attente"
    		
    		
    	}

		
	
}