/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import org.apache.log4j.Logger;

import Serveur.Controlleurs.Serveur;

/**
 *
 * @author Carbon5
 */
public class PanOrdreReparation extends javax.swing.JPanel {

    /**
     * Creates new form PanTest
     */
    public PanOrdreReparation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	
    	// TODO : recupération depuis la liste static dans RepairCard,
    	// 		  affichage des véhicules dans un tableau
    	//        ajout des champs de préférence indif et veto et enregistrement en base
    	//        récup des préférences et ajout dans les champs modifiables
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID vehicule", "Parking", "Degre d'urgence"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ORDRE DE REPARATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
        
        dayCriteria = new javax.swing.JLabel();
        timeCriteria = new javax.swing.JLabel();
        indif = new javax.swing.JLabel();
        veto = new javax.swing.JLabel();
        
        dayCriteria.setText("Jours passés dans le dépôt");
        timeCriteria.setText("Temps de réparation");
        indif.setText("Indifférence");
        veto.setText("Véto");
        
        indifDays = new javax.swing.JTextField();
        vetoDays = new javax.swing.JTextField();
        indifTime = new javax.swing.JTextField();
        vetoTime = new javax.swing.JTextField();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    
    private javax.swing.JLabel dayCriteria;
    private javax.swing.JLabel timeCriteria;
    private javax.swing.JLabel indif;
    private javax.swing.JLabel veto;
    
    private javax.swing.JTextField indifDays;
    private javax.swing.JTextField vetoDays;
    private javax.swing.JTextField indifTime;
    private javax.swing.JTextField vetoTime;
    
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    final static Logger logger = Logger.getLogger(Serveur.class);
    // End of variables declaration//GEN-END:variables
}
