/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import javax.swing.*;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carbon5
 */
public class PanParking extends javax.swing.JPanel {

    /**
     * Creates new form PanParking
     */
    public PanParking() throws SQLException {
        initComponents();
        this.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("PARKING");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    class RsTableModel extends AbstractTableModel {
        private Vector colHeaders;
        private Vector tbData;
        
        /**
         * Class constructor
         * @param rsData
         * @throws SQLException 
         */
        public RsTableModel(ResultSet rsData) throws SQLException {
            ResultSetMetaData rsMeta = rsData.getMetaData();
            int count = rsMeta.getColumnCount();

            tbData = new Vector();
            colHeaders = new Vector(count);

            for(int i = 1; i <= count; i++){
                colHeaders.addElement(rsMeta.getColumnName(i));
            }

            while (rsData.next()){
                Vector dataRow = new Vector(count);
                for(int i = 1; i <= count; i++){
                    dataRow.addElement(rsData.getObject(i));
                }
                tbData.addElement(dataRow);
            }
        }
        @Override
        public String getColumnName(int column) {
            return  (String) (colHeaders.elementAt(column));
        }
        
        @Override
        public int getRowCount() { return tbData.size(); }

        @Override
        public int getColumnCount() { return colHeaders.size(); }

        @Override
        public Object getValueAt(int row, int column) {
            Vector rowData = (Vector)(tbData.elementAt(row));
            return rowData.elementAt(column);
        }
        
        public void setData(){
        super.fireTableDataChanged();
}
    };
    
    /**
     * Method fill data to table
     * @throws SQLException 
     */
    protected void fillTable() throws SQLException{
        try{
            String url = "jdbc:mysql://localhost:3306/carbon5";
            String user = "root";
            String pwd = "";
            Connection connect = DriverManager.getConnection(url, user, pwd);
            String queryString = "SELECT * FROM Parking";
            Statement stm = connect.createStatement();
            ResultSet rs = stm.executeQuery(queryString);
            RsTableModel model = new RsTableModel(rs);
            this.jTable1.setModel(model);
            model.setData();
        } catch (Exception e){
            e.printStackTrace();
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
