/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.table.AbstractTableModel;

import Modele.Parking;

/**
 *
 * @author Carbon5
 */
public class PanParking extends javax.swing.JPanel {

    /**
     * Creates new form PanParking
     */
    public PanParking() throws SQLException {
        initComponents();
        this.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("PARKING");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
    }
    
    public class RsTableModel extends AbstractTableModel {
            private ArrayList<Parking> parkings ;
            private String[] columns ; 

            public RsTableModel(ArrayList<Parking> listParking){
              super();
              parkings = listParking ;
              columns = new String[]{"Num parking","Nom parking","Capacity"};
            }

            // Number of column of your table
            public int getColumnCount() {
              return columns.length ;
            }

            // Number of row of your table
            public int getRowCount() {
              return parkings.size();
            }

            // The object to render in a cell
            public Object getValueAt(int row, int col) {
              Parking parking = parkings.get(row);
              switch(col) {
                case 0: return parking.getNumParking();
                case 1: return parking.getNameParking();
                case 2: return parking.getCapacity();
                default: return null;
              }
            }
            // Optional, the name of your column
            public String getColumnName(int col) {
              return columns[col] ;
            }
        }
    
    /**
     * Method fill data to table
     * @throws SQLException 
     */
    protected void fillTable() throws SQLException{
        try{

            RsTableModel model = new RsTableModel(Parking.getAllParkings());
            this.jTable1.setModel(model);
        } catch (Exception e){
            e.printStackTrace();
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
