/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carbon5
 */
public class PanParking extends javax.swing.JPanel {

    /**
     * Creates new form PanParking
     */
    public PanParking() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        
        String url = "jdbc:mysql://localhost:3306/carbon5";
        String user = "root";
        String pwd = "";
        Connection con = DriverManager.getConnection(url, user, pwd);
        String queryString = "SELECT * FROM Parking";
        Statement stm = con.createStatement();
        ResultSet rs = stm.executeQuery(queryString);
        String col[] = {"Numero du parking","Nom du parking","Capacite"};
        String cont[][] = new String[10][3];
        int i = 0;
        while (rs.next()){
            int id = rs.getInt("NumParking");
            String nom = rs.getString("NomParking");
            int capacity = rs.getInt("Capacity");
            cont[i][0] = id + "";
            cont[i][1] = nom;
            cont[i][2] = capacity + "";
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(cont, col);
        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("PARKING");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
