/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import java.awt.event.ActionEvent;

import java.time.LocalDate;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import org.apache.log4j.Logger;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

import Client.Controlleurs.ServerConnect;
import Modele.Defect;
import Modele.Place;
import Modele.TypeCar;
import Serveur.Controlleurs.Serveur;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.UIManager;
import javax.swing.SwingConstants;

/**
 *
 * @author Carbon5
 */
public class test extends javax.swing.JPanel {
	ArrayList<String> datapanne = new ArrayList<String>();
	String panne=null;
	String listPanne="";
	ArrayList<String> PanneLabel = new ArrayList<String>();
	
    /**
     * Creates new form PanAjoutVehicule
     */
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	jScrollPane = new javax.swing.JScrollPane();
    	jLabel 	= new javax.swing.JLabel();
        jLabelviewpanne	= new javax.swing.JLabel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jComboBox1 = new JComboBox<>();
        jComboBox2 = new JComboBox<>();
        jComboBox5 = new JComboBox<>();
        jTextField1 = new JTextField();
        jTextField2 = new JTextField();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });
        Commentaires=new JTextArea();

        jLabel1.setText("AJOUTER DU VEHICULE");
        jLabel.setText("Liste motif :");
        jLabel2.setText("Num puce");

        jLabel3.setText("Type vehicule");
        
        jLabel4.setText("Matricule");
        jLabel5.setText("Motif entree");
               
        jLabel6.setText("Date entrée:   "+LocalDate.now());
        jLabel7.setText("Commentaires");
        jLabel8.setText("Place");
        
        DefaultComboBoxModel<String> modelCar = new DefaultComboBoxModel<String>();
        for (TypeCar typecar : TypeCar.getAllTypeCar()){
        	
        	modelCar.addElement(typecar.getType());
        }
        
        jComboBox1 = new JComboBox<String>(modelCar);
               
        DefaultComboBoxModel<String> modelpanne = new DefaultComboBoxModel<String>();
        for (Defect typecar : Defect.getAllDefect()){
        	modelpanne.addElement(typecar.getDescription());
        }
        jComboBox2= new JComboBox<String>(modelpanne);
        
        jComboBox2.addActionListener(new ItemAction(this));
        
        DefaultComboBoxModel<Integer> modelplace = new DefaultComboBoxModel<Integer>();
        for (Place aPlace : Place.getAllplace()){
        	
        	modelplace.addElement(aPlace.getNumPlace());
        }
        jComboBox5 = new JComboBox<Integer>(modelplace);
        
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new BoutonListener(this));
        
        jButton2.setText("Annuler");
        
        Commentaires.setColumns(20);
        Commentaires.setRows(6);
        jScrollPane.setViewportView(Commentaires);
                
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(10)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addComponent(jLabel5)
        				.addComponent(jLabel)
        				.addComponent(jLabelviewpanne)
        				.addComponent(jLabel6)
        				.addComponent(jLabel8)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel3)
        						.addComponent(jLabel4)
        						.addComponent(jLabel2)
        						.addComponent(jButton1)
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jLabel7)))
        					.addGap(15)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jComboBox1, 0, 110, Short.MAX_VALUE)
        						.addComponent(jComboBox2, 0, 110, Short.MAX_VALUE)
        						.addComponent(jComboBox5, 0, 110, Short.MAX_VALUE)
        						.addComponent(jTextField1)
        						.addComponent(jTextField2)
        						.addComponent(jButton2, Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(Commentaires, GroupLayout.PREFERRED_SIZE, 189, 189)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jScrollPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))))
        			.addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addComponent(jLabel)
        			.addComponent(jLabelviewpanne)
        			.addComponent(jLabel6)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(jComboBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(10)
        							.addComponent(Commentaires, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jLabel7))
        					.addGap(11))
        				.addComponent(jScrollPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton2)
        				.addComponent(jButton1))
        			.addGap(49))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton2;
    private JComboBox<String> jComboBox1;
    private JComboBox<String> jComboBox2;
    private JComboBox<String> jComboBox2_1;
    private JComboBox<Integer> jComboBox5;
    private JList<String> jmotif;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel;
    private JLabel jLabel7;
    private JLabel jLabelviewpanne;
    private JLabel jLabel8;
    private JScrollPane jScrollPane;
    private JTextField jTextField1;
	private JTextField jTextField2;
    final static Logger logger = Logger.getLogger(Serveur.class);
    private JTextArea Commentaires;
    // End of variables declaration//GEN-END:variables
    
    
    class ItemAction implements ActionListener{
    	JPanel frame=null;

    	/**
     	* Class constructor
     	* @param f 
     	*/
    	public ItemAction(JPanel f){
    		this.frame=f;
    	}
	
    	/**
    	 * Method generate component action
    	 * @param arg0 
    	 */
    	int i=0;
    	int count=0;
    	public void actionPerformed(ActionEvent e) {
    		  
    		if (count<3){
    	    	  panne= ""+(String) jComboBox2.getSelectedItem()+"";
	    	      datapanne.add(panne);
	    	      PanneLabel.add(panne);
	    	      String temp=PanneLabel.get(i)+"    ";
	    	      listPanne+=temp;
	    	      jLabelviewpanne.setText(listPanne);
	    	      i++;
	    	      count++;
    		}
    		else
    			JOptionPane.showMessageDialog(frame, "Attention pas plus de 3 pannes ");
    		
    	    }                 
      }
    
    /**
 	* Class BoutonListener listens button AJOUTER
 	*/
    class BoutonListener implements ActionListener{
    	JPanel frame=null;

    	/**
     	* Class constructor
     	* @param f 
     	*/
    	public BoutonListener  (JPanel f){
    		this.frame=f;
    	}
	
    	/**
    	 * Method generate component action
    	 * @param arg0 
    	 */
    	
    	public void actionPerformed(ActionEvent arg0){
    		
    		String typeCar = ""+(String) jComboBox1.getSelectedItem()+"";
    		String numPuce = jTextField1.getText();
    		String matricule = jTextField2.getText();
    		String place = ""+jComboBox5.getSelectedItem()+"";
    		ArrayList<String> data = new ArrayList<String>();
    		data.add(numPuce);
    		data.add(typeCar);
    		data.add(matricule);
    		data.add(place);
    		
    		for(String D: datapanne){
        		data.add(D);
    		}
    		
    		////////A faire : place et motif entrée////////////////
    		
    		//data.add(""+User.getAllUsers().get(0).getId());
    		String identifier = "AjoutVehicule";
    		logger.info("Entrée de"+numPuce);
    		new ServerConnect(data, identifier, frame);
    		
    	}
	}
}
