

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package r0;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

/**
 *
 * @author Christophe G
 */
public class addCar extends javax.swing.JFrame {

    
    JOptionPane jop1,jop2,jop3;
public addCar() {
        

initComponents();

//Importantion de la connexion

Statement st2 =null;

    try{
            st2 = Connexion.getInstance().createStatement();
    }

    catch(SQLException e){
        e.printStackTrace();
    }


    try{

    ResultSet rs=st2.executeQuery("SELECT * FROM marque ");

    while(rs.next()){
        jMarque.addItem(rs.getString("Libelle"));
    }
    
    rs.close();
    st2.close();
    }
    catch(Exception e)
    {
    e.printStackTrace();
    }
    }

/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
   
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jlabelModele = new javax.swing.JLabel();
        jLabelModele = new javax.swing.JLabel();
        jModele = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jKm = new javax.swing.JTextField();
        jMarque = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jim = new javax.swing.JTextField();
        jButtonEffacer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(153, 204, 255));
        jInternalFrame1.setTitle("Ajout d'un nouveau véhicule");
        jInternalFrame1.setVisible(true);

        jlabelModele.setForeground(new java.awt.Color(51, 51, 51));
        jlabelModele.setText("Marque");

        jLabelModele.setText("Modele");

        jModele.setText(" ");
        jModele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModeleActionPerformed(evt);
            }
        });

        jButtonValider.setText("Valider ");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jLabel1.setText("KM");

        jMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMarqueActionPerformed(evt);
            }
        });

        jLabel2.setText("Immatriculation");

        jim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimActionPerformed(evt);
            }
        });

        jButtonEffacer.setText("Effacer");
        jButtonEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1Layout.setHorizontalGroup(
        	jInternalFrame1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jInternalFrame1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jInternalFrame1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jInternalFrame1Layout.createSequentialGroup()
        					.addComponent(jlabelModele)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jMarque, 0, 99, Short.MAX_VALUE)
        					.addGap(6))
        				.addGroup(jInternalFrame1Layout.createSequentialGroup()
        					.addComponent(jLabel1)
        					.addGap(32)
        					.addComponent(jKm, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
        					.addGap(0, 21, Short.MAX_VALUE)))
        			.addGroup(jInternalFrame1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jInternalFrame1Layout.createSequentialGroup()
        					.addComponent(jLabelModele)
        					.addGap(28)
        					.addComponent(jModele, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        					.addGap(25))
        				.addGroup(jInternalFrame1Layout.createSequentialGroup()
        					.addComponent(jLabel2)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jim, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        					.addGap(26))))
        		.addGroup(jInternalFrame1Layout.createSequentialGroup()
        			.addGap(153)
        			.addComponent(jButtonValider)
        			.addGap(40)
        			.addComponent(jButtonEffacer)
        			.addGap(0, 53, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
        	jInternalFrame1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jInternalFrame1Layout.createSequentialGroup()
        			.addGap(44)
        			.addGroup(jInternalFrame1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jMarque, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jlabelModele)
        				.addComponent(jLabelModele)
        				.addComponent(jModele, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
        			.addGroup(jInternalFrame1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(jKm, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2)
        				.addComponent(jim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(114)
        			.addGroup(jInternalFrame1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButtonValider)
        				.addComponent(jButtonEffacer))
        			.addContainerGap())
        );
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {                                               

        
        
Statement st2 =null;

    try{
    st2 = Connexion.getInstance().createStatement();}

    catch(SQLException e){
    e.printStackTrace();}     
       
    try{        
        

        String lib = jMarque.getSelectedItem().toString();
        System.out.print(lib);
        String query = "SELECT idMarque FROM marque WHERE Libelle='"+lib+"' ";
        System.out.print(query);
        ResultSet rs1= st2.executeQuery(query);
        String id = null;

    while(rs1.next()){
        
        id= rs1.getString("idmarque"); // nom=nomrs.GETSTRING(nom de la conlonne bdd)
        System.out.print(id);
}
   
// Requete qui insert l'id , le prix , l'im,le modele , le km d'apres la valeurs rentrées

        String query2= "Insert INTO vehicule (prix,Imatriculation,Modele,kilometrage,idMarque,disponibilité)VALUES (?,?,?,?,'"+id+"',1) ";
   
// remplissage des trous avec les valeurs des boutons
   
        PreparedStatement prepare  = Connexion.getInstance().prepareStatement(query2);
        prepare.setString(2,jim.getText());
        prepare.setString(3, jModele.getText());
        prepare.setString(4, jKm.getText());
   
//Execution de la requete

        prepare.executeUpdate();
          
        }catch(Exception e){
    
        e.printStackTrace();
    
        }
    
    }                                              

    
    
    
    private void jModeleActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jMarqueActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jimActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

     
jKm.setText("");
jim.setText("");
jModele.setText("");

// TODO add your handling code here:
    }                                        


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonEffacer;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JTextField jKm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelModele;
    private javax.swing.JComboBox jMarque;
    private javax.swing.JTextField jModele;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jim;
    private javax.swing.JLabel jlabelModele;
    // End of variables declaration                   
}
